name: push docker image

on:
  push:
    branches:
      - "main"
      - "hotfix"

jobs:
  build_and_push:
    name: build_and_push (${{ matrix.docker.repo }})
    strategy:
      matrix:
        docker:
          - repo: planetariumhq/9c-bridge
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: login
        run: |
          docker login \
            --username '${{ secrets.DOCKER_USERNAME }}' \
            --password '${{ secrets.DOCKER_ACCESS_TOKEN }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build-and-push
        run: |
          docker buildx build . \
            --platform linux/arm64/v8,linux/amd64 \
            --tag ${{ matrix.docker.repo }}:git-${{ github.sha }} \
            --push
